import About from "components/about";
import CoreFeature from "components/coreFeature";
import NavBar from "components/navBar";
import PageFooter from "components/PageFooter";
import PopularCourse from "components/PopularCourse";
import PricePlan from "components/pricePlan";
import Testimonials from "components/testimonials";
import Head from "next/head";
import React from "react";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/router";
import { Fragment, useEffect } from "react";

export const getStaticProps = async ({ locale }) => ({
  props: { ...(await serverSideTranslations(locale, ["common"])) },
});
const Home = () => {
  const { locale } = useRouter();
  useEffect(() => {
    const dir = locale == "ar" ? "rtl" : "ltr";
    const title = document.querySelector("html").setAttribute("dir", dir);
    document.querySelector("html").setAttribute("lang", locale);
    document.title = title;
  }, [locale]);
  return (
    <Fragment>
      <Head>
        <title>learning - landing </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <About />
      <CoreFeature />
      <PopularCourse />
      <Testimonials />
      <PricePlan />
      <PageFooter />
    </Fragment>
  );
};
export default Home;
